import type {
  ExpectedPaymentRecord,
  NormalizedPaymentProofRecord,
  BankStatementTransaction,
  TimelineEvent,
} from "./types";
import type { ReconciliationCase } from "./types";

// ─── Expected Payments ───────────────────────────────────────────────────────

export const demoExpectedPayments: ExpectedPaymentRecord[] = [
  {
    schemaVersion: "1.0.0",
    expectedPaymentId: "INV-1001",
    invoiceNumber: "INV-1001",
    issueDate: "2026-05-18",
    dueDate: "2026-05-25",
    creditor: { name: "MyCompany Sdn Bhd", normalizedName: "MYCOMPANY SDN BHD" },
    debtor: { name: "ABC Singapore Pte Ltd", normalizedName: "ABC SINGAPORE PTE LTD" },
    creditorAccount: null,
    debtorAccount: null,
    invoiceCurrency: "USD",
    amountDue: { value: "100.00", currency: "USD" },
    expectedSettlementCurrency: "MYR",
    paymentReference: { raw: "INV1001", normalized: "INV1001" },
    reconciliationStatus: "OPEN",
    debtorReference: null,
    purchaseOrderReference: null,
    paymentTerms: "Net 7",
    outstandingAmount: null,
    sourceFileId: "invoice-file-001",
    sourceRowNumber: 1,
    fieldConfidence: { invoiceNumber: 1, amountDue: 1, issueDate: 1, dueDate: 1 },
    evidenceSpans: [],
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    expectedPaymentId: "INV-1002",
    invoiceNumber: "INV-1002",
    issueDate: "2026-05-19",
    dueDate: "2026-05-26",
    creditor: { name: "MyCompany Sdn Bhd", normalizedName: "MYCOMPANY SDN BHD" },
    debtor: { name: "TechGlobal Inc", normalizedName: "TECHGLOBAL INC" },
    creditorAccount: null,
    debtorAccount: null,
    invoiceCurrency: "USD",
    amountDue: { value: "500.00", currency: "USD" },
    expectedSettlementCurrency: "MYR",
    paymentReference: { raw: "INV1002", normalized: "INV1002" },
    reconciliationStatus: "OPEN",
    debtorReference: null,
    purchaseOrderReference: null,
    paymentTerms: "Net 7",
    outstandingAmount: null,
    sourceFileId: "invoice-file-001",
    sourceRowNumber: 2,
    fieldConfidence: { invoiceNumber: 1, amountDue: 1, issueDate: 1, dueDate: 1 },
    evidenceSpans: [],
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    expectedPaymentId: "INV-1003",
    invoiceNumber: "INV-1003",
    issueDate: "2026-05-18",
    dueDate: "2026-05-25",
    creditor: { name: "MyCompany Sdn Bhd", normalizedName: "MYCOMPANY SDN BHD" },
    debtor: { name: "Pacific Solutions Ltd", normalizedName: "PACIFIC SOLUTIONS LTD" },
    creditorAccount: null,
    debtorAccount: null,
    invoiceCurrency: "USD",
    amountDue: { value: "200.00", currency: "USD" },
    expectedSettlementCurrency: "MYR",
    paymentReference: { raw: "INV1003", normalized: "INV1003" },
    reconciliationStatus: "OPEN",
    debtorReference: null,
    purchaseOrderReference: null,
    paymentTerms: "Net 7",
    outstandingAmount: null,
    sourceFileId: "invoice-file-001",
    sourceRowNumber: 3,
    fieldConfidence: { invoiceNumber: 1, amountDue: 1, issueDate: 1, dueDate: 1 },
    evidenceSpans: [],
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    expectedPaymentId: "INV-1004",
    invoiceNumber: "INV-1004",
    issueDate: "2026-05-20",
    dueDate: "2026-05-27",
    creditor: { name: "MyCompany Sdn Bhd", normalizedName: "MYCOMPANY SDN BHD" },
    debtor: { name: "Digital Wave Pte Ltd", normalizedName: "DIGITAL WAVE PTE LTD" },
    creditorAccount: null,
    debtorAccount: null,
    invoiceCurrency: "SGD",
    amountDue: { value: "350.00", currency: "SGD" },
    expectedSettlementCurrency: "MYR",
    paymentReference: { raw: "INV1004", normalized: "INV1004" },
    reconciliationStatus: "OPEN",
    debtorReference: null,
    purchaseOrderReference: null,
    paymentTerms: "Net 7",
    outstandingAmount: null,
    sourceFileId: "invoice-file-001",
    sourceRowNumber: 4,
    fieldConfidence: { invoiceNumber: 1, amountDue: 1, issueDate: 1, dueDate: 1 },
    evidenceSpans: [],
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    expectedPaymentId: "INV-1005",
    invoiceNumber: "INV-1005",
    issueDate: "2026-05-19",
    dueDate: "2026-05-26",
    creditor: { name: "MyCompany Sdn Bhd", normalizedName: "MYCOMPANY SDN BHD" },
    debtor: { name: "Global Ventures Corp", normalizedName: "GLOBAL VENTURES CORP" },
    creditorAccount: null,
    debtorAccount: null,
    invoiceCurrency: "USD",
    amountDue: { value: "750.00", currency: "USD" },
    expectedSettlementCurrency: "MYR",
    paymentReference: { raw: "INV1005", normalized: "INV1005" },
    reconciliationStatus: "OPEN",
    debtorReference: null,
    purchaseOrderReference: null,
    paymentTerms: "Net 7",
    outstandingAmount: null,
    sourceFileId: "invoice-file-001",
    sourceRowNumber: 5,
    fieldConfidence: { invoiceNumber: 1, amountDue: 1, issueDate: 1, dueDate: 1 },
    evidenceSpans: [],
    warnings: [],
  },
];

// ─── Payment Proofs ───────────────────────────────────────────────────────────

export const demoPaymentProofs: NormalizedPaymentProofRecord[] = [
  {
    schemaVersion: "1.0.0",
    proofId: "PROOF-001",
    sourceFileId: "proof_001.png",
    financialPayload: {
      documentType: "bank_advice",
      paymentStatus: "ACSC",
      paymentStatusLabel: "Settled",
      rawPaymentStatus: "SETTLED",
      debtor: { name: "ABC Singapore", normalizedName: "ABC SINGAPORE" },
      creditor: { name: null, normalizedName: null },
      debtorAccount: null,
      creditorAccount: null,
      paidAmount: { value: "100.00", currency: "USD" },
      paymentDate: "2026-05-20",
      valueDate: null,
      bookingDate: null,
      reference: { raw: "INV1001", normalized: "INV1001" },
      providerTransactionId: null,
      providerOrBankName: null,
      invoiceIds: [],
      endToEndId: null,
      uetr: null,
      feeAmount: null,
      netAmount: null,
      sourceAmount: null,
      targetAmount: null,
      exchangeRateInformation: null,
      remittanceInformation: { raw: "INV1001", structured: null },
      rawText: null,
    },
    aiMetadata: {
      extractionRoute: "parse_image_ocr",
      overallConfidence: 0.91,
      fieldConfidence: { paidAmount: 0.97, reference: 0.86, debtorName: 0.91, paymentDate: 0.88 },
      evidenceSpans: [],
      requiresManualReview: false,
      warnings: [],
    },
    normalizationMetadata: {
      normalizedAt: "2026-05-23T12:30:01+08:00",
      toolsUsed: ["normalize_party_name", "normalize_reference"],
      warnings: [],
    },
  },
  {
    schemaVersion: "1.0.0",
    proofId: "PROOF-002",
    sourceFileId: "proof_002.pdf",
    financialPayload: {
      documentType: "swift_confirmation",
      paymentStatus: "ACSC",
      paymentStatusLabel: "Settled",
      rawPaymentStatus: "SETTLED",
      debtor: { name: "TechGlobal Inc", normalizedName: "TECHGLOBAL INC" },
      creditor: { name: null, normalizedName: null },
      debtorAccount: null,
      creditorAccount: null,
      paidAmount: { value: "500.00", currency: "USD" },
      paymentDate: "2026-05-21",
      valueDate: null,
      bookingDate: null,
      reference: { raw: "INV-1002", normalized: "INV1002" },
      providerTransactionId: null,
      providerOrBankName: null,
      invoiceIds: [],
      endToEndId: null,
      uetr: null,
      feeAmount: null,
      netAmount: null,
      sourceAmount: null,
      targetAmount: null,
      exchangeRateInformation: null,
      remittanceInformation: { raw: "INV-1002", structured: null },
      rawText: null,
    },
    aiMetadata: {
      extractionRoute: "parse_pdf_text",
      overallConfidence: 0.96,
      fieldConfidence: { paidAmount: 0.99, reference: 0.94, debtorName: 0.95, paymentDate: 0.96 },
      evidenceSpans: [],
      requiresManualReview: false,
      warnings: [],
    },
    normalizationMetadata: {
      normalizedAt: "2026-05-23T12:30:02+08:00",
      toolsUsed: ["normalize_party_name", "normalize_reference"],
      warnings: [],
    },
  },
  {
    schemaVersion: "1.0.0",
    proofId: "PROOF-003",
    sourceFileId: "proof_003.pdf",
    financialPayload: {
      documentType: "remittance_advice",
      paymentStatus: "ACSC",
      paymentStatusLabel: "Settled",
      rawPaymentStatus: "SETTLED",
      debtor: { name: "Pacific Solutions", normalizedName: "PACIFIC SOLUTIONS" },
      creditor: { name: null, normalizedName: null },
      debtorAccount: null,
      creditorAccount: null,
      paidAmount: { value: "200.00", currency: "USD" },
      paymentDate: "2026-05-19",
      valueDate: null,
      bookingDate: null,
      reference: { raw: "PAC-MAY-003", normalized: "PACMAY003" },
      providerTransactionId: null,
      providerOrBankName: null,
      invoiceIds: [],
      endToEndId: null,
      uetr: null,
      feeAmount: null,
      netAmount: null,
      sourceAmount: null,
      targetAmount: null,
      exchangeRateInformation: null,
      remittanceInformation: { raw: "PAC-MAY-003", structured: null },
      rawText: null,
    },
    aiMetadata: {
      extractionRoute: "parse_pdf_table",
      overallConfidence: 0.89,
      fieldConfidence: { paidAmount: 0.96, reference: 0.72, debtorName: 0.89, paymentDate: 0.92 },
      evidenceSpans: [],
      requiresManualReview: false,
      warnings: [],
    },
    normalizationMetadata: {
      normalizedAt: "2026-05-23T12:30:03+08:00",
      toolsUsed: ["normalize_party_name", "normalize_reference"],
      warnings: [],
    },
  },
  {
    schemaVersion: "1.0.0",
    proofId: "PROOF-004",
    sourceFileId: "proof_004.png",
    financialPayload: {
      documentType: "bank_advice",
      paymentStatus: "ACSC",
      paymentStatusLabel: "Settled",
      rawPaymentStatus: "SETTLED",
      debtor: { name: "Digital Wave", normalizedName: "DIGITAL WAVE" },
      creditor: { name: null, normalizedName: null },
      debtorAccount: null,
      creditorAccount: null,
      paidAmount: { value: "350.00", currency: "SGD" },
      paymentDate: "2026-05-20",
      valueDate: null,
      bookingDate: null,
      reference: { raw: "INV1004", normalized: "INV1004" },
      providerTransactionId: null,
      providerOrBankName: null,
      invoiceIds: [],
      endToEndId: null,
      uetr: null,
      feeAmount: null,
      netAmount: null,
      sourceAmount: null,
      targetAmount: null,
      exchangeRateInformation: null,
      remittanceInformation: { raw: "INV1004", structured: null },
      rawText: null,
    },
    aiMetadata: {
      extractionRoute: "parse_image_ocr",
      overallConfidence: 0.93,
      fieldConfidence: { paidAmount: 0.98, reference: 0.95, debtorName: 0.93, paymentDate: 0.91 },
      evidenceSpans: [],
      requiresManualReview: false,
      warnings: [],
    },
    normalizationMetadata: {
      normalizedAt: "2026-05-23T12:30:04+08:00",
      toolsUsed: ["normalize_party_name", "normalize_reference"],
      warnings: [],
    },
  },
];

// ─── Bank Transactions ────────────────────────────────────────────────────────

export const demoBankTransactions: BankStatementTransaction[] = [
  {
    schemaVersion: "1.0.0",
    internalTxId: "BANK-001",
    accountId: "ACC-MYR-001",
    bookingDate: "2026-05-21",
    valueDate: null,
    creditDebitIndicator: "CRDT",
    amount: { value: "423.80", currency: "MYR" },
    acctSvcrRef: null,
    normalizedReference: "INV1001",
    endToEndId: null,
    txId: null,
    debtorName: "ABC SG TRANSFER INV1001",
    debtorNormalizedName: "ABC SG TRANSFER",
    debtorAccount: null,
    creditorName: null,
    creditorNormalizedName: null,
    creditorAccount: null,
    remittanceInformation: { raw: "INV1001", structured: null },
    description: "ABC SG TRANSFER INV1001",
    rawDescription: "ABC SG TRANSFER INV1001",
    sourceFileId: "bank-statement-001",
    sourceRowNumber: 1,
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    internalTxId: "BANK-002",
    accountId: "ACC-MYR-001",
    bookingDate: "2026-05-22",
    valueDate: null,
    creditDebitIndicator: "CRDT",
    amount: { value: "2119.00", currency: "MYR" },
    acctSvcrRef: null,
    normalizedReference: "INV1002",
    endToEndId: null,
    txId: null,
    debtorName: "TECHGLOBAL INC TT",
    debtorNormalizedName: "TECHGLOBAL INC",
    debtorAccount: null,
    creditorName: null,
    creditorNormalizedName: null,
    creditorAccount: null,
    remittanceInformation: { raw: "INV1002", structured: null },
    description: "TECHGLOBAL INC TT",
    rawDescription: "TECHGLOBAL INC TT",
    sourceFileId: "bank-statement-001",
    sourceRowNumber: 2,
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    internalTxId: "BANK-003",
    accountId: "ACC-MYR-001",
    bookingDate: "2026-05-20",
    valueDate: null,
    creditDebitIndicator: "CRDT",
    amount: { value: "812.40", currency: "MYR" },
    acctSvcrRef: null,
    normalizedReference: null,
    endToEndId: null,
    txId: null,
    debtorName: "PACIFIC TRANSFER",
    debtorNormalizedName: "PACIFIC TRANSFER",
    debtorAccount: null,
    creditorName: null,
    creditorNormalizedName: null,
    creditorAccount: null,
    remittanceInformation: { raw: null, structured: null },
    description: "PACIFIC TRANSFER",
    rawDescription: "PACIFIC TRANSFER",
    sourceFileId: "bank-statement-001",
    sourceRowNumber: 3,
    warnings: [],
  },
  {
    schemaVersion: "1.0.0",
    internalTxId: "BANK-004",
    accountId: "ACC-MYR-001",
    bookingDate: "2026-05-21",
    valueDate: null,
    creditDebitIndicator: "CRDT",
    amount: { value: "1123.50", currency: "MYR" },
    acctSvcrRef: null,
    normalizedReference: "INV1004",
    endToEndId: null,
    txId: null,
    debtorName: "DIGITAL WAVE PTE LTD",
    debtorNormalizedName: "DIGITAL WAVE PTE LTD",
    debtorAccount: null,
    creditorName: null,
    creditorNormalizedName: null,
    creditorAccount: null,
    remittanceInformation: { raw: "INV1004", structured: null },
    description: "DIGITAL WAVE PTE LTD",
    rawDescription: "DIGITAL WAVE PTE LTD",
    sourceFileId: "bank-statement-001",
    sourceRowNumber: 4,
    warnings: [],
  },
];

// ─── Reconciliation Cases ─────────────────────────────────────────────────────

export const demoReconciliationCases: ReconciliationCase[] = [
  {
    id: "RECON-001",
    expected_payment: demoExpectedPayments[0]!,
    payment_proof: demoPaymentProofs[0]!,
    bank_transaction: demoBankTransactions[0]!,
    status: "AUTO_MATCHED",
    score: { reference_match: 35, amount_fx_match: 28, date_proximity: 15, name_similarity: 14, extraction_confidence: 4, total: 96 },
    fx_scenarios: [
      { scenario_name: "Invoice Date", fx_date: "2026-05-18", fx_rate: 4.22, expected_local_amount: 422.00, variance: 1.80, variance_percentage: 0.43, is_best_match: false },
      { scenario_name: "Payment Date", fx_date: "2026-05-20", fx_rate: 4.25, expected_local_amount: 425.00, variance: 1.20, variance_percentage: 0.28, is_best_match: false },
      { scenario_name: "Bank Date", fx_date: "2026-05-21", fx_rate: 4.238, expected_local_amount: 423.80, variance: 0.00, variance_percentage: 0.00, is_best_match: true },
    ],
    best_fx_scenario: { scenario_name: "Bank Date", fx_date: "2026-05-21", fx_rate: 4.238, expected_local_amount: 423.80, variance: 0.00, variance_percentage: 0.00, is_best_match: true },
    fee_hypothesis: null,
    human_action_required: false,
    reason: "Reference exact match, amount matches with bank-date FX rate, date proximity within 1 day, sender name highly similar.",
    created_at: "2026-05-23T12:30:05+08:00",
  },
  {
    id: "RECON-002",
    expected_payment: demoExpectedPayments[1]!,
    payment_proof: demoPaymentProofs[1]!,
    bank_transaction: demoBankTransactions[1]!,
    status: "LIKELY_MATCHED",
    score: { reference_match: 35, amount_fx_match: 25, date_proximity: 10, name_similarity: 15, extraction_confidence: 5, total: 90 },
    fx_scenarios: [
      { scenario_name: "Invoice Date", fx_date: "2026-05-19", fx_rate: 4.24, expected_local_amount: 2120.00, variance: 1.00, variance_percentage: 0.05, is_best_match: false },
      { scenario_name: "Payment Date", fx_date: "2026-05-21", fx_rate: 4.238, expected_local_amount: 2119.00, variance: 0.00, variance_percentage: 0.00, is_best_match: true },
      { scenario_name: "Bank Date", fx_date: "2026-05-22", fx_rate: 4.26, expected_local_amount: 2130.00, variance: 11.00, variance_percentage: 0.52, is_best_match: false },
    ],
    best_fx_scenario: { scenario_name: "Payment Date", fx_date: "2026-05-21", fx_rate: 4.238, expected_local_amount: 2119.00, variance: 0.00, variance_percentage: 0.00, is_best_match: true },
    fee_hypothesis: null,
    human_action_required: true,
    reason: "Reference exact match, amount matches with payment-date FX. Date gap of 3 days triggers human approval recommendation.",
    created_at: "2026-05-23T12:30:08+08:00",
  },
  {
    id: "RECON-003",
    expected_payment: demoExpectedPayments[2]!,
    payment_proof: demoPaymentProofs[2]!,
    bank_transaction: demoBankTransactions[2]!,
    status: "NEEDS_REVIEW",
    score: { reference_match: 0, amount_fx_match: 15, date_proximity: 15, name_similarity: 12, extraction_confidence: 4, total: 46 },
    fx_scenarios: [
      { scenario_name: "Invoice Date", fx_date: "2026-05-18", fx_rate: 4.22, expected_local_amount: 844.00, variance: 31.60, variance_percentage: 3.74, is_best_match: true },
      { scenario_name: "Payment Date", fx_date: "2026-05-19", fx_rate: 4.24, expected_local_amount: 848.00, variance: 35.60, variance_percentage: 4.20, is_best_match: false },
      { scenario_name: "Bank Date", fx_date: "2026-05-20", fx_rate: 4.25, expected_local_amount: 850.00, variance: 37.60, variance_percentage: 4.42, is_best_match: false },
    ],
    best_fx_scenario: { scenario_name: "Invoice Date", fx_date: "2026-05-18", fx_rate: 4.22, expected_local_amount: 844.00, variance: 31.60, variance_percentage: 3.74, is_best_match: true },
    fee_hypothesis: { possible_fee: 31.60, explanation: "Possible bank/intermediary fee or FX spread. Expected RM844.00, received RM812.40. Difference of RM31.60 (3.74%) could indicate processing fees." },
    human_action_required: true,
    reason: "Reference mismatch (proof shows PAC-MAY-003, no bank reference). Amount variance > 2% triggers mandatory review. Possible fee/spread hypothesis generated.",
    created_at: "2026-05-23T12:30:12+08:00",
  },
  {
    id: "RECON-004",
    expected_payment: demoExpectedPayments[3]!,
    payment_proof: demoPaymentProofs[3]!,
    bank_transaction: demoBankTransactions[3]!,
    status: "AUTO_MATCHED",
    score: { reference_match: 35, amount_fx_match: 30, date_proximity: 15, name_similarity: 14, extraction_confidence: 5, total: 99 },
    fx_scenarios: [
      { scenario_name: "Payment Date", fx_date: "2026-05-20", fx_rate: 3.21, expected_local_amount: 1123.50, variance: 0.00, variance_percentage: 0.00, is_best_match: true },
    ],
    best_fx_scenario: { scenario_name: "Payment Date", fx_date: "2026-05-20", fx_rate: 3.21, expected_local_amount: 1123.50, variance: 0.00, variance_percentage: 0.00, is_best_match: true },
    fee_hypothesis: null,
    human_action_required: false,
    reason: "Reference exact match, amount matches perfectly with payment-date SGD/MYR rate, date proximity within 1 day, sender name matches.",
    created_at: "2026-05-23T12:30:15+08:00",
  },
  {
    id: "RECON-005",
    expected_payment: demoExpectedPayments[4]!,
    payment_proof: null,
    bank_transaction: null,
    status: "UNMATCHED",
    score: { reference_match: 0, amount_fx_match: 0, date_proximity: 0, name_similarity: 0, extraction_confidence: 0, total: 0 },
    fx_scenarios: [],
    best_fx_scenario: null,
    fee_hypothesis: null,
    human_action_required: true,
    reason: "No payment proof uploaded for this expected payment. No matching bank deposit found within the expected time window.",
    created_at: "2026-05-23T12:30:18+08:00",
  },
];

// ─── Timeline Events ──────────────────────────────────────────────────────────

export const demoTimelineEvents: TimelineEvent[] = [
  {
    id: "evt-001",
    timestamp: "2026-05-23T12:30:00+08:00",
    agent: "Extraction Agent",
    action: "inspect_file",
    toolName: "inspect_file",
    inputSummary: "file: proof_001.png",
    resultSummary: "type: scanned_image — routing to OCR/vision extraction",
    reasoning: "File is a scanned PNG image. Routing to OCR/vision extraction.",
    warnings: [],
  },
  {
    id: "evt-002",
    timestamp: "2026-05-23T12:30:01+08:00",
    agent: "Extraction Agent",
    action: "parse_image_ocr",
    toolName: "parse_image_ocr",
    inputSummary: "file: proof_001.png",
    resultSummary: "payer: ABC Singapore | amount: USD 100.00 | ref: INV1001 | confidence: 0.94",
    reasoning: "OCR extraction successful. Amount and reference fields have high confidence.",
    observedConfidence: 0.94,
    warnings: [],
  },
  {
    id: "evt-003",
    timestamp: "2026-05-23T12:30:02+08:00",
    agent: "Extraction Agent",
    action: "inspect_file",
    toolName: "inspect_file",
    inputSummary: "file: proof_002.pdf",
    resultSummary: "type: text_pdf, has_text_layer: true — routing to parse_pdf_text",
    reasoning: "PDF has embedded text layer. No OCR needed.",
    warnings: [],
  },
  {
    id: "evt-004",
    timestamp: "2026-05-23T12:30:02+08:00",
    agent: "Extraction Agent",
    action: "parse_pdf_text",
    toolName: "parse_pdf_text",
    inputSummary: "file: proof_002.pdf",
    resultSummary: "payer: TechGlobal Inc | amount: USD 500.00 | ref: INV-1002 | confidence: 0.96",
    reasoning: "Text extraction successful. All fields extracted with high confidence.",
    observedConfidence: 0.96,
    warnings: [],
  },
  {
    id: "evt-005",
    timestamp: "2026-05-23T12:30:03+08:00",
    agent: "Code Tools",
    action: "fetch_fx_rate",
    toolName: "fetch_fx_rate",
    inputSummary: "from: USD, to: MYR, date: 2026-05-20",
    resultSummary: "rate: 4.25, source: fallback_fx_table",
    reasoning: "Payment proof date is a relevant settlement-date candidate.",
    warnings: [],
  },
  {
    id: "evt-006",
    timestamp: "2026-05-23T12:30:04+08:00",
    agent: "Code Tools",
    action: "calculate_fx_scenarios",
    toolName: "calculate_fx_scenarios",
    inputSummary: "expected: USD 100.00, dates: [2026-05-18, 2026-05-20, 2026-05-21]",
    resultSummary: "best match: bank date (4.238) → RM423.80 exact match",
    reasoning: "Bank-date FX (4.238) produces exact match with bank deposit (RM423.80).",
    warnings: [],
  },
  {
    id: "evt-007",
    timestamp: "2026-05-23T12:30:04+08:00",
    agent: "Code Tools",
    action: "score_candidate",
    toolName: "score_candidate",
    inputSummary: "proof: PROOF-001, bank_txn: BANK-001",
    resultSummary: "score: 96/100 — reference: 35, amount/fx: 28, date: 15, name: 14, confidence: 4",
    reasoning: "Strong reference match, amount within 0.5% variance with best FX scenario, dates are close.",
    observedConfidence: 0.96,
    warnings: [],
  },
  {
    id: "evt-008",
    timestamp: "2026-05-23T12:30:05+08:00",
    agent: "Code Tools",
    action: "classify_match",
    toolName: "classify_match",
    inputSummary: "score: 96, signals: [reference_exact, amount_match, date_close]",
    resultSummary: "AUTO_MATCHED — no human review required",
    reasoning: "Score 96 >= 95 threshold. All critical signals are strong. No competing candidates.",
    warnings: [],
  },
  {
    id: "evt-009",
    timestamp: "2026-05-23T12:30:10+08:00",
    agent: "Code Tools",
    action: "detect_competing_candidates",
    toolName: "detect_competing_candidates",
    inputSummary: "proof: PROOF-003",
    resultSummary: "competing: false, candidates: 1",
    reasoning: "Only one plausible bank transaction matches the amount range.",
    warnings: [],
  },
  {
    id: "evt-010",
    timestamp: "2026-05-23T12:30:11+08:00",
    agent: "Code Tools",
    action: "evaluate_fee_hypothesis",
    toolName: "evaluate_fee_hypothesis",
    inputSummary: "expected_myr: 844.00, received_myr: 812.40",
    resultSummary: "possible_fee: RM31.60 (3.74%) — hypothesis: bank_fee_or_spread",
    reasoning: "Variance of 3.74% exceeds 2% threshold. Generating fee hypothesis.",
    warnings: [],
  },
  {
    id: "evt-011",
    timestamp: "2026-05-23T12:30:12+08:00",
    agent: "Code Tools",
    action: "classify_match",
    toolName: "classify_match",
    inputSummary: "score: 46, signals: [no_reference_match, variance_over_2%, name_similar]",
    resultSummary: "NEEDS_REVIEW — human approval required",
    reasoning: "Score 46 < 60 threshold. Reference mismatch and high variance trigger mandatory review.",
    warnings: [],
  },
  {
    id: "evt-012",
    timestamp: "2026-05-23T12:30:18+08:00",
    agent: "Code Tools",
    action: "classify_match",
    toolName: "classify_match",
    inputSummary: "score: 0, signals: [no_proof, no_bank_match]",
    resultSummary: "UNMATCHED — generate discrepancy artifact",
    reasoning: "No payment proof uploaded. No bank deposit found within expected window.",
    warnings: [],
  },
  {
    id: "evt-013",
    timestamp: "2026-05-23T12:30:20+08:00",
    agent: "Code Tools",
    action: "generate_artifact",
    toolName: "generate_artifact",
    inputSummary: "case: RECON-005, type: discrepancy",
    resultSummary: "email draft generated for user review",
    reasoning: "Unmatched case requires follow-up communication.",
    warnings: [],
  },
];
